name:  fudan sports
on:
  # schedule:
    # - cron: "17 0,12 * * *"  # scheduled at 06:17 & 13:17 (UTC+8) everyday
  workflow_dispatch:

jobs:
  code_format_check:
    name: Code Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: reserve
        run: |
          python3 ./main.py '${{ secrets.FUDAN }}'
